name: CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'app/**'
      - 'models/**'
      - 'Dockerfile'
      - 'uv.lock'

env:
  SSH_HOST: ${{ contains(github.ref, 'main') && secrets.SSH_PRODUCTION_HOST || secrets.SSH_TESTING_HOST }}
  IMAGE_TAG: ${{ contains(github.ref, 'main') && 'stable' || 'latest' }}
  REGISTRY_HOST: 908027417939.dkr.ecr.sa-east-1.amazonaws.com 

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: docker/setup-buildx-action@master

      - uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: docker/build-push-action@master
        with:
          push: true
          tags: ${{ env.REGISTRY_HOST }}/api-moderation:${{ env.IMAGE_TAG }}

      - uses: appleboy/ssh-action@master
        with:
          script: deploy
          command_timeout: '2m'
          username: ec2-user
          host: ${{ env.SSH_HOST }}
          key: ${{ secrets.SSH_ROOT_KEY }}
